import funcoes_cafeteria as f
nome = input("coloque o nome da bebida: ")
preco_base = int(input("insira o preco base: "))
acressimo = float(input("insira o acressimo: "))
nome_acompanhamento= input("insira o acompanhamento ")
preco_acompanhamento = float(input("insira o preco do acompanhamento: "))
desconto = float(input("insira o desconto (opcional): "))
taxa_servico = float(input("insira a taxa de serico: "))
preco_cafe = f.calcular_preco_cafe(preco_base,acressimo)
preco_total_acompanhamento = f.calcular_acompanhamento(preco_acompanhamento,desconto)
valor1,valor2= f.calcular_totais(preco_cafe,preco_total_acompanhamento)
f.resumo_item(nome,valor1)
f.resumo_item(nome_acompanhamento, valor2)
print (f"total a pagar = R${valor1+valor2}")
print(f"taxa de servico = {taxa_servico}")